/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalPainelRouteImport } from './routes/portal.painel'
import { Route as PortalIndiqueRouteImport } from './routes/portal.indique'
import { Route as AuthenticatedSolicitacoesRouteImport } from './routes/_authenticated/solicitacoes'
import { Route as AuthenticatedServidoresRouteImport } from './routes/_authenticated/servidores'
import { Route as AuthenticatedRenovacaoRouteImport } from './routes/_authenticated/renovacao'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAdminAssinantesRouteImport } from './routes/_authenticated/admin.assinantes'
import { Route as ApiPublicZapiStatusRouteImport } from './routes/api/public/zapi/status'
import { Route as ApiPublicZapiQrRouteImport } from './routes/api/public/zapi/qr'
import { Route as ApiPublicZapiDisconnectRouteImport } from './routes/api/public/zapi/disconnect'
import { Route as ApiPublicPortalVerifyOtpRouteImport } from './routes/api/public/portal/verify-otp'
import { Route as ApiPublicPortalRequestOtpRouteImport } from './routes/api/public/portal/request-otp'
import { Route as ApiPublicPortalRenewRequestRouteImport } from './routes/api/public/portal/renew-request'
import { Route as ApiPublicPortalMeRouteImport } from './routes/api/public/portal/me'
import { Route as ApiPublicPortalLogoutRouteImport } from './routes/api/public/portal/logout'
import { Route as ApiPublicPortalLoginPasswordRouteImport } from './routes/api/public/portal/login-password'
import { Route as ApiPublicHooksAutoChargesRouteImport } from './routes/api/public/hooks/auto-charges'
import { Route as AuthenticatedAdminAssinantesIdRouteImport } from './routes/_authenticated/admin.assinantes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPainelRoute = PortalPainelRouteImport.update({
  id: '/portal/painel',
  path: '/portal/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndiqueRoute = PortalIndiqueRouteImport.update({
  id: '/portal/indique',
  path: '/portal/indique',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolicitacoesRoute =
  AuthenticatedSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServidoresRoute = AuthenticatedServidoresRouteImport.update({
  id: '/servidores',
  path: '/servidores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRenovacaoRoute = AuthenticatedRenovacaoRouteImport.update({
  id: '/renovacao',
  path: '/renovacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAssinantesRoute =
  AuthenticatedAdminAssinantesRouteImport.update({
    id: '/admin/assinantes',
    path: '/admin/assinantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicZapiStatusRoute = ApiPublicZapiStatusRouteImport.update({
  id: '/api/public/zapi/status',
  path: '/api/public/zapi/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZapiQrRoute = ApiPublicZapiQrRouteImport.update({
  id: '/api/public/zapi/qr',
  path: '/api/public/zapi/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZapiDisconnectRoute = ApiPublicZapiDisconnectRouteImport.update({
  id: '/api/public/zapi/disconnect',
  path: '/api/public/zapi/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPortalVerifyOtpRoute =
  ApiPublicPortalVerifyOtpRouteImport.update({
    id: '/api/public/portal/verify-otp',
    path: '/api/public/portal/verify-otp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPortalRequestOtpRoute =
  ApiPublicPortalRequestOtpRouteImport.update({
    id: '/api/public/portal/request-otp',
    path: '/api/public/portal/request-otp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPortalRenewRequestRoute =
  ApiPublicPortalRenewRequestRouteImport.update({
    id: '/api/public/portal/renew-request',
    path: '/api/public/portal/renew-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPortalMeRoute = ApiPublicPortalMeRouteImport.update({
  id: '/api/public/portal/me',
  path: '/api/public/portal/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPortalLogoutRoute = ApiPublicPortalLogoutRouteImport.update({
  id: '/api/public/portal/logout',
  path: '/api/public/portal/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPortalLoginPasswordRoute =
  ApiPublicPortalLoginPasswordRouteImport.update({
    id: '/api/public/portal/login-password',
    path: '/api/public/portal/login-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoChargesRoute =
  ApiPublicHooksAutoChargesRouteImport.update({
    id: '/api/public/hooks/auto-charges',
    path: '/api/public/hooks/auto-charges',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAssinantesIdRoute =
  AuthenticatedAdminAssinantesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminAssinantesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/renovacao': typeof AuthenticatedRenovacaoRoute
  '/servidores': typeof AuthenticatedServidoresRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/portal/indique': typeof PortalIndiqueRoute
  '/portal/painel': typeof PortalPainelRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/assinantes': typeof AuthenticatedAdminAssinantesRouteWithChildren
  '/admin/assinantes/$id': typeof AuthenticatedAdminAssinantesIdRoute
  '/api/public/hooks/auto-charges': typeof ApiPublicHooksAutoChargesRoute
  '/api/public/portal/login-password': typeof ApiPublicPortalLoginPasswordRoute
  '/api/public/portal/logout': typeof ApiPublicPortalLogoutRoute
  '/api/public/portal/me': typeof ApiPublicPortalMeRoute
  '/api/public/portal/renew-request': typeof ApiPublicPortalRenewRequestRoute
  '/api/public/portal/request-otp': typeof ApiPublicPortalRequestOtpRoute
  '/api/public/portal/verify-otp': typeof ApiPublicPortalVerifyOtpRoute
  '/api/public/zapi/disconnect': typeof ApiPublicZapiDisconnectRoute
  '/api/public/zapi/qr': typeof ApiPublicZapiQrRoute
  '/api/public/zapi/status': typeof ApiPublicZapiStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/renovacao': typeof AuthenticatedRenovacaoRoute
  '/servidores': typeof AuthenticatedServidoresRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/portal/indique': typeof PortalIndiqueRoute
  '/portal/painel': typeof PortalPainelRoute
  '/portal': typeof PortalIndexRoute
  '/admin/assinantes': typeof AuthenticatedAdminAssinantesRouteWithChildren
  '/admin/assinantes/$id': typeof AuthenticatedAdminAssinantesIdRoute
  '/api/public/hooks/auto-charges': typeof ApiPublicHooksAutoChargesRoute
  '/api/public/portal/login-password': typeof ApiPublicPortalLoginPasswordRoute
  '/api/public/portal/logout': typeof ApiPublicPortalLogoutRoute
  '/api/public/portal/me': typeof ApiPublicPortalMeRoute
  '/api/public/portal/renew-request': typeof ApiPublicPortalRenewRequestRoute
  '/api/public/portal/request-otp': typeof ApiPublicPortalRequestOtpRoute
  '/api/public/portal/verify-otp': typeof ApiPublicPortalVerifyOtpRoute
  '/api/public/zapi/disconnect': typeof ApiPublicZapiDisconnectRoute
  '/api/public/zapi/qr': typeof ApiPublicZapiQrRoute
  '/api/public/zapi/status': typeof ApiPublicZapiStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/renovacao': typeof AuthenticatedRenovacaoRoute
  '/_authenticated/servidores': typeof AuthenticatedServidoresRoute
  '/_authenticated/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/portal/indique': typeof PortalIndiqueRoute
  '/portal/painel': typeof PortalPainelRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/admin/assinantes': typeof AuthenticatedAdminAssinantesRouteWithChildren
  '/_authenticated/admin/assinantes/$id': typeof AuthenticatedAdminAssinantesIdRoute
  '/api/public/hooks/auto-charges': typeof ApiPublicHooksAutoChargesRoute
  '/api/public/portal/login-password': typeof ApiPublicPortalLoginPasswordRoute
  '/api/public/portal/logout': typeof ApiPublicPortalLogoutRoute
  '/api/public/portal/me': typeof ApiPublicPortalMeRoute
  '/api/public/portal/renew-request': typeof ApiPublicPortalRenewRequestRoute
  '/api/public/portal/request-otp': typeof ApiPublicPortalRequestOtpRoute
  '/api/public/portal/verify-otp': typeof ApiPublicPortalVerifyOtpRoute
  '/api/public/zapi/disconnect': typeof ApiPublicZapiDisconnectRoute
  '/api/public/zapi/qr': typeof ApiPublicZapiQrRoute
  '/api/public/zapi/status': typeof ApiPublicZapiStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/planos'
    | '/renovacao'
    | '/servidores'
    | '/solicitacoes'
    | '/portal/indique'
    | '/portal/painel'
    | '/portal/'
    | '/admin/assinantes'
    | '/admin/assinantes/$id'
    | '/api/public/hooks/auto-charges'
    | '/api/public/portal/login-password'
    | '/api/public/portal/logout'
    | '/api/public/portal/me'
    | '/api/public/portal/renew-request'
    | '/api/public/portal/request-otp'
    | '/api/public/portal/verify-otp'
    | '/api/public/zapi/disconnect'
    | '/api/public/zapi/qr'
    | '/api/public/zapi/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/planos'
    | '/renovacao'
    | '/servidores'
    | '/solicitacoes'
    | '/portal/indique'
    | '/portal/painel'
    | '/portal'
    | '/admin/assinantes'
    | '/admin/assinantes/$id'
    | '/api/public/hooks/auto-charges'
    | '/api/public/portal/login-password'
    | '/api/public/portal/logout'
    | '/api/public/portal/me'
    | '/api/public/portal/renew-request'
    | '/api/public/portal/request-otp'
    | '/api/public/portal/verify-otp'
    | '/api/public/zapi/disconnect'
    | '/api/public/zapi/qr'
    | '/api/public/zapi/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/planos'
    | '/_authenticated/renovacao'
    | '/_authenticated/servidores'
    | '/_authenticated/solicitacoes'
    | '/portal/indique'
    | '/portal/painel'
    | '/portal/'
    | '/_authenticated/admin/assinantes'
    | '/_authenticated/admin/assinantes/$id'
    | '/api/public/hooks/auto-charges'
    | '/api/public/portal/login-password'
    | '/api/public/portal/logout'
    | '/api/public/portal/me'
    | '/api/public/portal/renew-request'
    | '/api/public/portal/request-otp'
    | '/api/public/portal/verify-otp'
    | '/api/public/zapi/disconnect'
    | '/api/public/zapi/qr'
    | '/api/public/zapi/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PortalIndiqueRoute: typeof PortalIndiqueRoute
  PortalPainelRoute: typeof PortalPainelRoute
  PortalIndexRoute: typeof PortalIndexRoute
  ApiPublicHooksAutoChargesRoute: typeof ApiPublicHooksAutoChargesRoute
  ApiPublicPortalLoginPasswordRoute: typeof ApiPublicPortalLoginPasswordRoute
  ApiPublicPortalLogoutRoute: typeof ApiPublicPortalLogoutRoute
  ApiPublicPortalMeRoute: typeof ApiPublicPortalMeRoute
  ApiPublicPortalRenewRequestRoute: typeof ApiPublicPortalRenewRequestRoute
  ApiPublicPortalRequestOtpRoute: typeof ApiPublicPortalRequestOtpRoute
  ApiPublicPortalVerifyOtpRoute: typeof ApiPublicPortalVerifyOtpRoute
  ApiPublicZapiDisconnectRoute: typeof ApiPublicZapiDisconnectRoute
  ApiPublicZapiQrRoute: typeof ApiPublicZapiQrRoute
  ApiPublicZapiStatusRoute: typeof ApiPublicZapiStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/painel': {
      id: '/portal/painel'
      path: '/portal/painel'
      fullPath: '/portal/painel'
      preLoaderRoute: typeof PortalPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/indique': {
      id: '/portal/indique'
      path: '/portal/indique'
      fullPath: '/portal/indique'
      preLoaderRoute: typeof PortalIndiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solicitacoes': {
      id: '/_authenticated/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servidores': {
      id: '/_authenticated/servidores'
      path: '/servidores'
      fullPath: '/servidores'
      preLoaderRoute: typeof AuthenticatedServidoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/renovacao': {
      id: '/_authenticated/renovacao'
      path: '/renovacao'
      fullPath: '/renovacao'
      preLoaderRoute: typeof AuthenticatedRenovacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/assinantes': {
      id: '/_authenticated/admin/assinantes'
      path: '/admin/assinantes'
      fullPath: '/admin/assinantes'
      preLoaderRoute: typeof AuthenticatedAdminAssinantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/zapi/status': {
      id: '/api/public/zapi/status'
      path: '/api/public/zapi/status'
      fullPath: '/api/public/zapi/status'
      preLoaderRoute: typeof ApiPublicZapiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zapi/qr': {
      id: '/api/public/zapi/qr'
      path: '/api/public/zapi/qr'
      fullPath: '/api/public/zapi/qr'
      preLoaderRoute: typeof ApiPublicZapiQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zapi/disconnect': {
      id: '/api/public/zapi/disconnect'
      path: '/api/public/zapi/disconnect'
      fullPath: '/api/public/zapi/disconnect'
      preLoaderRoute: typeof ApiPublicZapiDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/verify-otp': {
      id: '/api/public/portal/verify-otp'
      path: '/api/public/portal/verify-otp'
      fullPath: '/api/public/portal/verify-otp'
      preLoaderRoute: typeof ApiPublicPortalVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/request-otp': {
      id: '/api/public/portal/request-otp'
      path: '/api/public/portal/request-otp'
      fullPath: '/api/public/portal/request-otp'
      preLoaderRoute: typeof ApiPublicPortalRequestOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/renew-request': {
      id: '/api/public/portal/renew-request'
      path: '/api/public/portal/renew-request'
      fullPath: '/api/public/portal/renew-request'
      preLoaderRoute: typeof ApiPublicPortalRenewRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/me': {
      id: '/api/public/portal/me'
      path: '/api/public/portal/me'
      fullPath: '/api/public/portal/me'
      preLoaderRoute: typeof ApiPublicPortalMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/logout': {
      id: '/api/public/portal/logout'
      path: '/api/public/portal/logout'
      fullPath: '/api/public/portal/logout'
      preLoaderRoute: typeof ApiPublicPortalLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/login-password': {
      id: '/api/public/portal/login-password'
      path: '/api/public/portal/login-password'
      fullPath: '/api/public/portal/login-password'
      preLoaderRoute: typeof ApiPublicPortalLoginPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-charges': {
      id: '/api/public/hooks/auto-charges'
      path: '/api/public/hooks/auto-charges'
      fullPath: '/api/public/hooks/auto-charges'
      preLoaderRoute: typeof ApiPublicHooksAutoChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/assinantes/$id': {
      id: '/_authenticated/admin/assinantes/$id'
      path: '/$id'
      fullPath: '/admin/assinantes/$id'
      preLoaderRoute: typeof AuthenticatedAdminAssinantesIdRouteImport
      parentRoute: typeof AuthenticatedAdminAssinantesRoute
    }
  }
}

interface AuthenticatedAdminAssinantesRouteChildren {
  AuthenticatedAdminAssinantesIdRoute: typeof AuthenticatedAdminAssinantesIdRoute
}

const AuthenticatedAdminAssinantesRouteChildren: AuthenticatedAdminAssinantesRouteChildren =
  {
    AuthenticatedAdminAssinantesIdRoute: AuthenticatedAdminAssinantesIdRoute,
  }

const AuthenticatedAdminAssinantesRouteWithChildren =
  AuthenticatedAdminAssinantesRoute._addFileChildren(
    AuthenticatedAdminAssinantesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedRenovacaoRoute: typeof AuthenticatedRenovacaoRoute
  AuthenticatedServidoresRoute: typeof AuthenticatedServidoresRoute
  AuthenticatedSolicitacoesRoute: typeof AuthenticatedSolicitacoesRoute
  AuthenticatedAdminAssinantesRoute: typeof AuthenticatedAdminAssinantesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedRenovacaoRoute: AuthenticatedRenovacaoRoute,
  AuthenticatedServidoresRoute: AuthenticatedServidoresRoute,
  AuthenticatedSolicitacoesRoute: AuthenticatedSolicitacoesRoute,
  AuthenticatedAdminAssinantesRoute:
    AuthenticatedAdminAssinantesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PortalIndiqueRoute: PortalIndiqueRoute,
  PortalPainelRoute: PortalPainelRoute,
  PortalIndexRoute: PortalIndexRoute,
  ApiPublicHooksAutoChargesRoute: ApiPublicHooksAutoChargesRoute,
  ApiPublicPortalLoginPasswordRoute: ApiPublicPortalLoginPasswordRoute,
  ApiPublicPortalLogoutRoute: ApiPublicPortalLogoutRoute,
  ApiPublicPortalMeRoute: ApiPublicPortalMeRoute,
  ApiPublicPortalRenewRequestRoute: ApiPublicPortalRenewRequestRoute,
  ApiPublicPortalRequestOtpRoute: ApiPublicPortalRequestOtpRoute,
  ApiPublicPortalVerifyOtpRoute: ApiPublicPortalVerifyOtpRoute,
  ApiPublicZapiDisconnectRoute: ApiPublicZapiDisconnectRoute,
  ApiPublicZapiQrRoute: ApiPublicZapiQrRoute,
  ApiPublicZapiStatusRoute: ApiPublicZapiStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
